apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-vol1

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: <volume_id>
    fsType: ext4
