apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod
  labels:
    app: nginx-app
    tier: front-end

spec:
  containers:
    - name: nginx-container
      image: nginx
      securityContext:
        runAsUser: 1000
        capabilities:
          add:
            - "MAC_ADMIN"