apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
    tier: front-end

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        tier: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
