apiVersion: v1
kind: Service

metadata:
  name: nginx-nodePort-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008 # can be 30000 - 32767
  selector:
    app: nginx-app
    tier: front-end