apiVersion: v1
kind: Pod

metadata:
  name: my-app

spec:
  containers:
    - name: frontend
      image: nginx
      volumeMounts:
        - mountPath: /var/www/html
          name: my-vol
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: pvc1