apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: developer

rules:
  - apiGroups:
      - "" # "" means core API group
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
      - "update"
      - "delete"
      - "create"
  - apiGroups:
      - ""
    resources:
      - "ConfigMap"
    verbs:
      - create